# Arquivo de configuração para o Jekyll
# Adicionando um tema básico para ajudar na formatação

title: Guia Tomorrow MMO Brasil
description: Wiki completa e não oficial para jogadores de Tomorrow MMO

# Especifica o tema Jekyll a ser usado
theme: minima

# Exclui arquivos ou pastas que não devem ser copiados para o site final
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
