# Arquivo de configuração básico para o Jekyll
# Este arquivo pode ficar vazio ou conter configurações adicionais no futuro.
# Sua presença ajuda o GitHub Pages a processar os arquivos Markdown.

# title: Seu Título da Wiki (Opcional)
# description: Uma breve descrição (Opcional)

# theme: minima (Opcional: para usar um tema padrão do Jekyll)
title: Guia Tomorrow MMO Brasil
